service :
  db:
    image: postgres:16-alpine
    container_name: 69-s1-db
    ports:
      - 54327:5432
    environments:
      - POSTGRES_PASSWORD=220947
      - POSTGRES_USER=thitinunt
      - POSTGRES_DB=thitinunt
    volumes:
      - ./data:/var/lib/postgresql/data  
